# -*- coding: utf-8 -*-
"""CV LAB4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11462RjvPFakW4YuSVfAAPmXtqJqEeYDV
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
def show_comparison(original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original Grayscale image')
  plt.axis('off')
  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title('Sobel edge detection')
  plt.axis('off')
  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title('Prewitt edge detection')
  plt.axis('off')
  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title('Canny edge detection')
  plt.axis('off')
  plt.tight_layout()
  plt.show()
original = cv2.imread('/content/building.jpg',0)
if original is None:
  print('Error image not found')
else:
  sobelx = cv2.Sobel(original,cv2.CV_64F,1,0,ksize=3)
  sobely = cv2.Sobel(original,cv2.CV_64F,0,1,ksize=3)
  sobel_combined=cv2.magnitude(sobelx,sobely)
  kernelx=np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
  kernely=np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
  prewittx=cv2.filter2D(original, -1, kernelx)
  prewitty=cv2.filter2D(original, -1, kernely)
  prewitt_combined=prewittx+prewitty
  sobel=np.uint8(np.absolute(sobel_combined))
  prewitt=np.uint8(np.absolute(prewitt_combined))
  canny = cv2.Canny(original,100,200)
  show_comparison(original,sobel,prewitt,canny)